---
vnf:
    name:        vpp-lantency-mb
    description: Single-VM VNF descriptor for the VPP latency middlebox
    external-connections:
    -   name:              eth0
        type:              mgmt
        description:       General purpose interface
        VNFC:              linux-VM
        local_iface_name:  eth0
    VNFC:
    -   name:        linux-VM
        description:
        image name:  ubuntu-16.04-server-cloudimg-amd64-disk1
        vcpus: 2
        ram:   2048
        disk:  10
        bridge-ifaces:
        -   name:      eth0
            # floating-ip: True
            vpci:      "0000:00:10.0"
        -   name:      eth1
            floating-ip: True
            vpci:      "0000:00:12.0"
        -   name:      eth2
            floating-ip: True
            vpci:      "0000:00:12.0"
        numas: []
        boot-data:
            key-pairs:
            -  ssh-rsa <copy your public SSH keys here>
            boot-data-drive: true
            config-files:
            -   content: |
                    deb [trusted=yes] https://nexus.fd.io/content/repositories/fd.io.stable.1801.ubuntu.xenial.main/ ./
                dest: /etc/apt/sources.list.d/99fd.io.list
                permissions: '0755'
                apt:
            -   content: |
                    #! /bin/bash
                    /root/update-sys.sys
                    /root/build-vpp.sh
                dest: /etc/rc.local
                permissions: '0755'
            -   content: |
                    #! /bin/bash
                    #
                    # Update the package list
                    apt -y update
                    apt -y upgrade
                    apt -y install linux-image-extra-virtual autoconf libtool ethtool make apt-show-versions
                    apt -y install vpp vpp-lib vpp-dev vpp-plugins vpp-api-python python-cffi
                dest: /root/update-sys.sys
                permissions: '0755'
            -   content: |
                    #!/bin/bash
                    PRJ=VPP-latency-middlebox-0.1
                    cd /root
                    date '+Starting: %d/%m/%Y %H:%M:%S' >> ${HOME}/install-vpp.log
                    # git clone https://github.com/mami-project/vpp-mb.git
                    wget -O ${PRJ}.tar.gz https://github.com/mami-project/VPP-latency-middlebox/archive/v0.1.tar.gz
                    tar -xvf ${PRJ}-mb.tar.gz
                    # Remove any installed vpp plugins
                    service vpp stop
                    rm /usr/lib/vpp_plugins/*.so >> ${HOME}/install-vpp.log
                    #
                    # Compile/Install MMB plugin
                    #
                    (cd /root/${PRJ}/mmb-plugin; autoreconf -fis; ./configure; make; make install; cd-)
                    sleep 2
                    service vpp start
                    sleep 5
                    service vpp status >> ${HOME}/install-vpp.log
                    date '+Finished: %d/%m/%Y %H:%M:%S' >> ${HOME}/install-vpp.log
                dest: /root/build-vpp.sh
                permissions: 0755
